import argparse

parser = argparse.ArgumentParser()

parser.add_argument('--seed', type=int, default=222)
parser.add_argument('--id', type=str, default='test')
parser.add_argument('--mode', type=str, default='train')
parser.add_argument('--model', type=str, default=None)
parser.add_argument('--test', type=str, default='test')
parser.add_argument('--epochs', type=int, default=100)
parser.add_argument('--ft_epoch', type=int, default=3)
parser.add_argument('--ckpts_id', type=str, default=None)
parser.add_argument('--step', type=int, default=0)

parser.add_argument('--local_rank', type=int, default=-1)
parser.add_argument('--nproc_per_node', type=int, default=-1)

parser.add_argument('--trained_ckpts', default='/home/chengkz/checkpoints/ofa/log/ofa_m1.0_t16_k1.0_222/model/model_300.pt')
parser.add_argument('--ofa_ckpts', default='/home/data_ti4_c/chengkz/scripts/OFA-large')
parser.add_argument('--ofa_ckpts_distill', default='/home/chengkz/checkpoints/ofa/OFA-large-caption-XEfinetuned')
parser.add_argument('--git', default="microsoft/git-large")
parser.add_argument('--git_distill', default="microsoft/git-large-coco")
parser.add_argument('--config_blip', default='./models/BLIP/caption_coco.yaml')
parser.add_argument('--config_blip_t', default='./models/BLIP/caption_coco_teacher.yaml')
parser.add_argument('--data_dir', default='./data')
parser.add_argument('--vocab', default='./data/vocab.pkl')
parser.add_argument('--train', default='./data/train.json')
parser.add_argument('--train_mix', default='./data/train_mix_cc12m_keyword_large.json')
parser.add_argument('--knowcap240', default='/home/chengkz/checkpoints/KnowCap_240')
parser.add_argument('--data_mode', default='mix')
parser.add_argument('--samples_dir', default='./examples/example_images')
parser.add_argument('--samples_out', default=None)
parser.add_argument('--pretrain_model', default=None)

parser.add_argument('--save_loss_freq', type=int, default=20)
parser.add_argument('--save_model_freq', type=int, default=100)
parser.add_argument('--log_dir', default='/home/chengkz/checkpoints/ofa/log/{}')

parser.add_argument('--batch_size', type=int, default=60)
parser.add_argument('--val_batch_size', type=int, default=25)
parser.add_argument('--num_workers', type=int, default=1)
parser.add_argument('--fixed_len', type=int, default=20)
parser.add_argument('--lr_enc', type=float, default=2e-5)
parser.add_argument('--learning_rate', type=float, default=7e-6)
parser.add_argument('--grad_clip', type=float, default=0.1)
parser.add_argument('--beam_num', type=int, default=5)
parser.add_argument('--gen_num', type=int, default=5)
parser.add_argument('--beam_alpha', type=float, default=1.0)
parser.add_argument('--length_penalty', type=float, default=1.0)
parser.add_argument('--multitask_weight', type=float, default=0.5)
parser.add_argument('--knowdistill_weight', type=float, default=1.0)
parser.add_argument('--data_ratio', type=float, default=1.0)
parser.add_argument('--label_smoothing', type=float, default=0.0)
parser.add_argument('--KD_temperature', type=float, default=8.0)

parser.add_argument('--image_dim', type=int, default=2048)
parser.add_argument('--embed_dim', type=int, default=512)
parser.add_argument('--hidden_dim', type=int, default=512)
parser.add_argument('--att_dim', type=int, default=1024)

parser.add_argument('--method', type=str, default=None)

config = parser.parse_args()
